<?php

/**
 * @file callbacks.inc
 *   Menu callbacks.
 */

/**
 * Menu page callback. User landing page, payment was successful.
 */
function kkb_epay_callback_back_success($id) {
}

/**
 * Menu page callback. User landing page, payment failed.
 */
function kkb_epay_callback_back_failure($id) {
}

/**
 * Menu page callback. Processing center response callback.
 */
function kkb_epay_callback_post_success($id) {
}

/**
 * Menu page callback. Processing center response callback.
 */
function kkb_epay_callback_post_failure($id) {
}

