<?php

/**
 * @file kkb_epay.module
 *   KKB 'Epay' authorization server support.
 */

/**
 * Prepares a complete valid form element ready to be submitted to the
 * authorization server.
 *
 * Form is prepared and returned in a form of Drupal's renderable array.
 * The caller party is free to modify the form before rendering it. The most
 * common reason to modify the form is to add/modify submit buttons or some
 * textual annotations.
 *
 * @warning
 *   The returned form is not a complete Drupal form that can be submitted back
 *   to the site and handled by drupal_build_form() function. This form must
 *   be submitted directly to the authorization server.
 *
 * @return
 *   Complete definition of a billing form in a form of a renderable array.
 */
function kkb_epay_create_billing_statement() {
  $form = array();

  return $form;
}

/**
 * Implements hook_menu().
 */
function kkb_epay_menu() {
  $items = array(
    'admin/config/services/epay' => array(
      'title'            => 'KKB Epay',
      'description'      => t('KKB Epay payments gateway configuration.'),
      'page callback'    => 'system_admin_menu_block_page',
      'access callback'  => 'user_access',
      'access arguments' => array('administer kkb_epay'),
      'file'             => 'system.admin.inc',
      'file path'        => drupal_get_path('module', 'system'),
      'type'             => MENU_NORMAL_ITEM,
    ),
    'admin/config/services/epay/debug' => array(
      'title'            => 'KKB Epay debugging mode',
      'description'      => t('Choose to send payments to a live gateway or a sandbox.'),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('kkb_epay_admin_debug_form'),
      'access callback'  => 'user_access',
      'access arguments' => array('administer kkb_epay'),
      'file'             => 'kkb_epay.admin.inc',
      'type'             => MENU_NORMAL_ITEM,
    ),
    'admin/config/services/epay/private-key' => array(
      'title'            => 'KKB Epay private key configuration',
      'description'      => t('Check the existing or add a new private key.'),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('kkb_epay_admin_private_key_form'),
      'access callback'  => 'user_access',
      'access arguments' => array('administer kkb_epay'),
      'file'             => 'kkb_epay.admin.inc',
      'type'             => MENU_NORMAL_ITEM,
    ),
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function kkb_epay_theme($existing, $type, $theme, $path) {
  $hooks = array();

  return $hooks;
}

/**
 * Implements hook_permission().
 */
function kkb_epay_permission() {
  return array(
    'administer kkb_epay' => array(
      'title' => t('Administer KKB Epay configuration'),
      'description' => t('Manage private keys and payments debugging mode.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Signs a message with the default key.
 *
 * @return string|NULL
 *   Returnes NULL if any errors happen. Otherwise, returns base64-encoded
 *   signature.
 */
function kkb_epay_sign_message($message) {
  $loader = new KkbEpay_DrupalKeyLoader();
  $loader->setDebug(kkb_epay_debug_status());

  if (!$loader->validateKey()) {
    drupal_set_message(t('Private key could not be loaded. Message will not be signed.'), 'error');
    return NULL;
  }

  $sign = new KkbEpay_Sign($loader->getKey());
  try {
    return $sign->sign64($message);
  }
  catch (KkbEpay_Exception $ex) {
    return NULL;
  }
}

/**
 * Checks a message signature with the default certificate.
 *
 * @param text $message
 *   Message whose signature must be verified.
 *
 * @param text $signature
 *   Base64-encoded signature of the message.
 *
 * @return boolean
 *   TRUE if signature was check without errors.
 *   FALSE otherwise.
 */
function kkb_epay_check_signature($message, $signature) {
  $certificate = new KkbEpay_DefaultBankCertificate();
  try {
    $checker = new KkbEpay_Checker($certificate);
    return $checker->check64($message, $signature);
  }
  catch (KkbEpay_Exception $ex) {
    return FALSE;
  }
}

/**
 * Returnes the current debugging status.
 *
 * @return boolean
 *   TRUE if debugging mode is turned on.
 *   FALSE if debugging mode is turned off.
 */
function kkb_epay_debug_status() {
  return (bool) variable_get('kkb_epay_debug_status', FALSE);
}

