<?php

/**
 * @file kkb_epay_uc.module
 *   Integration of kkb_epay module with Ubercart's payments system.
 *
 * Copyright (C) 2012, Victor Nikulshin
 *
 * This file is part of KKB Epay.
 *
 * KKB Epay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * KKB Epay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with KKB Epay.  If not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/**
 * Implements hook_uc_payment_method().
 */
function kkb_epay_uc_uc_payment_method() {
  $methods['kkb_epay'] = array(
    'name'       => t('KKB Epay'),
    'title'      => t('KKB Epay credit card processing center'),
    'desc'       => t('Pay with our bank cart securely at the <a href="https://epay.kkb.kz/">https://epay.kkb.kz/</a> processing center.'),
    'callback'   => 'kkb_epay_uc_method_callback',
    'weight'     => 1,
    'checkout'   => TRUE,
    'no_gateway' => TRUE,
    'redirect'   => 'kkb_epay_uc_redirect',
  );

  return $methods;
}

