<?php

/**
 * @file kkb_epay_uc.module
 *   Integration of kkb_epay module with Ubercart's payments system.
 *
 * Copyright (C) 2012, Victor Nikulshin
 *
 * This file is part of KKB Epay.
 *
 * KKB Epay is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * KKB Epay is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with KKB Epay.  If not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/**
 * Implements hook_uc_payment_method().
 */
function kkb_epay_uc_uc_payment_method() {
  $methods['kkb_epay'] = array(
    'name'       => t('KKB Epay'),
    'title'      => t('KKB Epay credit card processing center'),
    'desc'       => t('Pay with our bank cart securely at the <a href="https://epay.kkb.kz/">https://epay.kkb.kz/</a> processing center.'),
    'callback'   => 'kkb_epay_uc_method_callback',
    'weight'     => 1,
    'checkout'   => TRUE,
    'no_gateway' => TRUE,
    'redirect'   => 'kkb_epay_uc_redirect',
  );

  return $methods;
}

/**
 * Implements hook_uc_payment_method_callback().
 */
function kkb_epay_uc_method_callback($op, &$order, $form = NULL, &$form_state = NULL) {
  if ($op == 'cart-process') {
    if ($order->currency != 'KZT') {
      _kkb_epay_uc_unsupported_currency_warn($order);
      return FALSE;
    }
  }
}

/**
 * Form builder. Creates redirect form that is displayed after an order is
 * formed and is ready to be payed.
 */
function kkb_epay_uc_redirect($form, &$form_state, stdClass $uc_order) {
  if ($uc_order->currency != 'KZT') {
    _kkb_epay_uc_unsupported_currency_warn($uc_order);
    _kkb_epay_uc_unsupported_currency_log($uc_order);
    return array();
  }

  $account = user_load($uc_order->uid);
  $epay_order = new KkbEpay_Order($uc_order->order_id);
  $epay_order->setTengeAmount($uc_order->order_total);

  foreach ($uc_order->products as $p) {
    $epay_order->addItem(new KkbEpay_OrderItem($p->title, $p->price * $p->qty, $p->qty));
  }
  foreach ($uc_order->line_items as $i) {
    $epay_order->addItem(new KkbEpay_OrderItem($i['title'], $i['amount']));
  }

  $statement = drupal_get_form('kkb_epay_billing_statement', $epay_order, $account);

  // Add unique token for better security.
  $url = url('epay/back/success/' . $uc_order->order_id, array('absolute' => TRUE, 'query' => array(
    'token' => drupal_get_token('payment for order ' . $uc_order->order_id),
  )));
  $statement['BackLink']['#value'] = $url;

  return $statement;
}

/**
 * Creates an errors message for user to inform that an order uses a currency
 * that cannot be processed by the Epay gateway.
 */
function _kkb_epay_uc_unsupported_currency_warn($order) {
  $message = t(
    'This order cannot be payed with Epay processing center. Epay can accept payments only in Tenge. The currency of this order is %c.',
    array('%c' => $order->currency)
  );
  drupal_set_message($message, 'error');
}

/**
 * Logs an attempt to use Epay to pay for an order in unsupported currency.
 */
function _kkb_epay_uc_unsupported_currency_log($order) {
  watchdog(
    'kkb_epay',
    'An order in unsupported currency %c could not be processed by Epay.',
    array('%c' => $uc_order->currency),
    WATCHDOG_CRITICAL
  );
}

